# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: host_info.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'host_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhost_info.proto\x12\x07traffic\"\xf5\x01\n\x08HostInfo\x12\x0f\n\x07host_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\n\n\x02os\x18\x03 \x01(\t\x12\x0c\n\x04\x61rch\x18\x04 \x01(\t\x12\x16\n\x0ekernel_version\x18\x05 \x01(\t\x12\x35\n\ninterfaces\x18\x06 \x03(\x0b\x32!.traffic.HostInfo.InterfacesEntry\x12\x15\n\rboot_time_sec\x18\x07 \x01(\x03\x12\x13\n\x0bregister_ts\x18\x08 \x01(\x03\x1a\x31\n\x0fInterfacesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1bZ\x19traffic-agent/gen/trafficb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'host_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031traffic-agent/gen/traffic'
  _globals['_HOSTINFO_INTERFACESENTRY']._loaded_options = None
  _globals['_HOSTINFO_INTERFACESENTRY']._serialized_options = b'8\001'
  _globals['_HOSTINFO']._serialized_start=29
  _globals['_HOSTINFO']._serialized_end=274
  _globals['_HOSTINFO_INTERFACESENTRY']._serialized_start=225
  _globals['_HOSTINFO_INTERFACESENTRY']._serialized_end=274
# @@protoc_insertion_point(module_scope)
