services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1    
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "29092:29092"  # доступ снаружи (для ваших агентов на хост-машине)

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8
    environment:
      CLICKHOUSE_DB: netsentry
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: pass
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - 8123:8123

  db_app:
    image: postgres:16-alpine
    container_name: db_app
    environment:
      POSTGRES_USER: netsentry
      POSTGRES_PASSWORD: netsentry
      POSTGRES_DB: netsentry
    volumes:
      - postgres_data:/var/lib/postgresql/data

  analyzer:
    build:
      context: ./traffic-analyzer
    depends_on:
      - kafka
      - clickhouse
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      CLICKHOUSE_URL: jdbc:clickhouse://clickhouse:8123/netsentry
    restart: unless-stopped

  # Единый контейнер frontend (nginx) + backend (uvicorn), как в корневом Dockerfile
  app:
    build:
      context: ./app-service
    depends_on:
      - kafka
      - clickhouse
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      CLICKHOUSE_HOST: clickhouse
    ports:
      - "8080:8000"
    restart: unless-stopped

volumes:
  clickhouse_data:
  postgres_data: