# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x07traffic*:\n\x08HookType\x12\x0b\n\x07HOOK_TC\x10\x00\x12\x0c\n\x08HOOK_XDP\x10\x01\x12\x13\n\x0fHOOK_CGROUP_SKB\x10\x02*$\n\tDirection\x12\x0b\n\x07INGRESS\x10\x00\x12\n\n\x06\x45GRESS\x10\x01*K\n\x08Protocol\x12\x0f\n\x0bIPPROTO_TCP\x10\x00\x12\x0f\n\x0bIPPROTO_UDP\x10\x01\x12\x10\n\x0cIPPROTO_ICMP\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03\x42\x1bZ\x19traffic-agent/gen/trafficb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031traffic-agent/gen/traffic'
  _globals['_HOOKTYPE']._serialized_start=25
  _globals['_HOOKTYPE']._serialized_end=83
  _globals['_DIRECTION']._serialized_start=85
  _globals['_DIRECTION']._serialized_end=121
  _globals['_PROTOCOL']._serialized_start=123
  _globals['_PROTOCOL']._serialized_end=198
# @@protoc_insertion_point(module_scope)
