// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfprog

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type trafficPacketEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	SrcIp       uint32
	DstIp       uint32
	SrcPort     uint16
	DstPort     uint16
	PktLen      uint32
	Protocol    uint8
	HookType    uint8
	Direction   uint8
	Pad         uint8
	Ifindex     uint32
}

// loadTraffic returns the embedded CollectionSpec for traffic.
func loadTraffic() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrafficBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traffic: %w", err)
	}

	return spec, err
}

// loadTrafficObjects loads traffic and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trafficObjects
//	*trafficPrograms
//	*trafficMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrafficObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraffic()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trafficSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficSpecs struct {
	trafficProgramSpecs
	trafficMapSpecs
	trafficVariableSpecs
}

// trafficProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficProgramSpecs struct {
	CgSkbEgress  *ebpf.ProgramSpec `ebpf:"cg_skb_egress"`
	CgSkbIngress *ebpf.ProgramSpec `ebpf:"cg_skb_ingress"`
	TcClsEgress  *ebpf.ProgramSpec `ebpf:"tc_cls_egress"`
	TcClsIngress *ebpf.ProgramSpec `ebpf:"tc_cls_ingress"`
	XdpTraffic   *ebpf.ProgramSpec `ebpf:"xdp_traffic"`
}

// trafficMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// trafficVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficVariableSpecs struct {
	UnusedEvt *ebpf.VariableSpec `ebpf:"unused_evt"`
}

// trafficObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficObjects struct {
	trafficPrograms
	trafficMaps
	trafficVariables
}

func (o *trafficObjects) Close() error {
	return _TrafficClose(
		&o.trafficPrograms,
		&o.trafficMaps,
	)
}

// trafficMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *trafficMaps) Close() error {
	return _TrafficClose(
		m.Events,
	)
}

// trafficVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficVariables struct {
	UnusedEvt *ebpf.Variable `ebpf:"unused_evt"`
}

// trafficPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficPrograms struct {
	CgSkbEgress  *ebpf.Program `ebpf:"cg_skb_egress"`
	CgSkbIngress *ebpf.Program `ebpf:"cg_skb_ingress"`
	TcClsEgress  *ebpf.Program `ebpf:"tc_cls_egress"`
	TcClsIngress *ebpf.Program `ebpf:"tc_cls_ingress"`
	XdpTraffic   *ebpf.Program `ebpf:"xdp_traffic"`
}

func (p *trafficPrograms) Close() error {
	return _TrafficClose(
		p.CgSkbEgress,
		p.CgSkbIngress,
		p.TcClsEgress,
		p.TcClsIngress,
		p.XdpTraffic,
	)
}

func _TrafficClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traffic_bpfeb.o
var _TrafficBytes []byte
